setup.dashboards.enabled: true

# Forcing Elasticsearch index template 
setup.template.overwrite: true

setup.kibana.host: "https://kibana:5601"
setup.kibana.protocol: "https"
setup.kibana.ssl.enabled: true
setup.kibana.username: '${ELASTIC_USERNAME:}'
setup.kibana.password: '${ELASTIC_PASSWORD:}'
setup.kibana.ssl.certificate_authorities: ["/etc/pki/ca-trust/source/anchors/ca.crt"]
setup.kibana.ssl.certificate: ${CONFIG_DIR}/metricbeat.crt
setup.kibana.ssl.key: ${CONFIG_DIR}/metricbeat.key
setup.kibana.ssl.verification_mode: none

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true


processors:
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
  ssl.certificate_authorities: ["/etc/pki/ca-trust/source/anchors/ca.crt"]
  ssl.certificate: ${CONFIG_DIR}/metricbeat.crt
  ssl.key: ${CONFIG_DIR}/metricbeat.key
  index: metricbeat
