version: '3.3'

services:
  certs:
    container_name: certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    command: bash ${ELASTIC_DIR}/config/cert_gen.sh
    user: "0"
    volumes:
      - ./secrets:/secrets/
      - ./cert_gen.sh:${ELASTIC_DIR}/config/cert_gen.sh
      - ./instances.yml:${ELASTIC_DIR}/config/instances.yml:ro
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - elk

volumes:
  secrets:
    driver: local
  setup:
    driver: local

networks:
  elk:
    driver: bridge
